# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\github\PowerTrans\ui\settingWin.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(430, 420)
        Dialog.setMinimumSize(QtCore.QSize(350, 420))
        Dialog.setMaximumSize(QtCore.QSize(3500, 4200))
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setContentsMargins(-1, 3, -1, 3)
        self.gridLayout_2.setSpacing(3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox1 = QtWidgets.QGroupBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox1.sizePolicy().hasHeightForWidth())
        self.groupBox1.setSizePolicy(sizePolicy)
        self.groupBox1.setMinimumSize(QtCore.QSize(300, 150))
        self.groupBox1.setObjectName("groupBox1")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox1)
        self.verticalLayout_4.setContentsMargins(12, 1, 12, 1)
        self.verticalLayout_4.setSpacing(1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.groupBox1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(0, 20))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.cb_hostapi = QtWidgets.QComboBox(self.groupBox1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_hostapi.sizePolicy().hasHeightForWidth())
        self.cb_hostapi.setSizePolicy(sizePolicy)
        self.cb_hostapi.setMinimumSize(QtCore.QSize(300, 30))
        self.cb_hostapi.setMaximumSize(QtCore.QSize(16777215, 30))
        self.cb_hostapi.setObjectName("cb_hostapi")
        self.verticalLayout.addWidget(self.cb_hostapi)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 20))
        self.label.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.cb_audio = QtWidgets.QComboBox(self.groupBox1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_audio.sizePolicy().hasHeightForWidth())
        self.cb_audio.setSizePolicy(sizePolicy)
        self.cb_audio.setMinimumSize(QtCore.QSize(300, 30))
        self.cb_audio.setMaximumSize(QtCore.QSize(16777215, 30))
        self.cb_audio.setObjectName("cb_audio")
        self.verticalLayout_2.addWidget(self.cb_audio)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.gridLayout_2.addWidget(self.groupBox1, 0, 0, 1, 1)
        self.groupBox2 = QtWidgets.QGroupBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox2.sizePolicy().hasHeightForWidth())
        self.groupBox2.setSizePolicy(sizePolicy)
        self.groupBox2.setMinimumSize(QtCore.QSize(0, 180))
        self.groupBox2.setObjectName("groupBox2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox2)
        self.gridLayout.setContentsMargins(3, 3, 3, 3)
        self.gridLayout.setHorizontalSpacing(3)
        self.gridLayout.setVerticalSpacing(2)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 1, -1, 1)
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.buttonDrawVoice = QtWidgets.QPushButton(self.groupBox2)
        self.buttonDrawVoice.setMinimumSize(QtCore.QSize(80, 30))
        self.buttonDrawVoice.setStyleSheet("QWidget {\n"
"        background-color: #ffffff;  /* 背景颜色：白色 */\n"
"        color: #000000;             /* 文本颜色：黑色 */\n"
"        font-family: \"Helvetica Neue\", sans-serif; /* 字体类型：Helvetica Neue */\n"
"        font-size: 12px;            /* 字体大小 */\n"
"        font-weight: bold;        /* 字体加粗 */\n"
"        border: 1px solid #d1d1d1;  /* 边框颜色：浅灰色 */\n"
"        border-radius: 8px;         /* 圆角半径 */\n"
"        padding: 4px;              /* 内边距 */\n"
"    }\n"
"    QWidget:hover {\n"
"        background-color: #f5f5f5;  /* 悬停时的背景颜色：浅灰色 */\n"
"        border: 1px solid #c1c1c1;  /* 悬停时的边框颜色：稍深的灰色 */\n"
"    }\n"
"    QWidget:pressed {\n"
"        background-color: #e0e0e0;  /* 按下时的背景颜色：更深的灰色 */\n"
"        border: 1px solid #b1b1b1;  /* 按下时的边框颜色：更深的灰色 */\n"
"    }")
        self.buttonDrawVoice.setObjectName("buttonDrawVoice")
        self.horizontalLayout_2.addWidget(self.buttonDrawVoice)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.checkboxSaveFile = QtWidgets.QCheckBox(self.groupBox2)
        self.checkboxSaveFile.setMinimumSize(QtCore.QSize(100, 25))
        self.checkboxSaveFile.setObjectName("checkboxSaveFile")
        self.horizontalLayout_2.addWidget(self.checkboxSaveFile)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.widgetWave = QtWidgets.QWidget(self.groupBox2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetWave.sizePolicy().hasHeightForWidth())
        self.widgetWave.setSizePolicy(sizePolicy)
        self.widgetWave.setMinimumSize(QtCore.QSize(300, 100))
        self.widgetWave.setMaximumSize(QtCore.QSize(3000, 1000))
        self.widgetWave.setObjectName("widgetWave")
        self.verticalLayout_3.addWidget(self.widgetWave)
        self.gridLayout.addLayout(self.verticalLayout_3, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox2, 2, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(5, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 3, 0, 1, 1)
        self.groupbox0 = QtWidgets.QFrame(Dialog)
        self.groupbox0.setMinimumSize(QtCore.QSize(0, 60))
        self.groupbox0.setObjectName("groupbox0")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupbox0)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem4 = QtWidgets.QSpacerItem(42, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem4, 0, 0, 1, 1)
        self.buttonRun = QtWidgets.QPushButton(self.groupbox0)
        self.buttonRun.setMinimumSize(QtCore.QSize(100, 40))
        self.buttonRun.setMaximumSize(QtCore.QSize(100, 40))
        self.buttonRun.setStyleSheet("QWidget {\n"
"        background-color: #ffffff;  /* 背景颜色：白色 */\n"
"        color: #000000;             /* 文本颜色：黑色 */\n"
"        font-family: \"Helvetica Neue\", sans-serif; /* 字体类型：Helvetica Neue */\n"
"        font-size: 14px;            /* 字体大小 */\n"
"        font-weight: bold;        /* 字体加粗 */\n"
"        border: 1px solid #d1d1d1;  /* 边框颜色：浅灰色 */\n"
"        border-radius: 8px;         /* 圆角半径 */\n"
"        padding: 4px;              /* 内边距 */\n"
"    }\n"
"    QWidget:hover {\n"
"        background-color: #f5f5f5;  /* 悬停时的背景颜色：浅灰色 */\n"
"        border: 1px solid #c1c1c1;  /* 悬停时的边框颜色：稍深的灰色 */\n"
"    }\n"
"    QWidget:pressed {\n"
"        background-color: #e0e0e0;  /* 按下时的背景颜色：更深的灰色 */\n"
"        border: 1px solid #b1b1b1;  /* 按下时的边框颜色：更深的灰色 */\n"
"    }")
        self.buttonRun.setObjectName("buttonRun")
        self.gridLayout_3.addWidget(self.buttonRun, 0, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(41, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem5, 0, 2, 1, 1)
        self.buttonExit = QtWidgets.QPushButton(self.groupbox0)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonExit.sizePolicy().hasHeightForWidth())
        self.buttonExit.setSizePolicy(sizePolicy)
        self.buttonExit.setMinimumSize(QtCore.QSize(100, 40))
        self.buttonExit.setMaximumSize(QtCore.QSize(100, 40))
        self.buttonExit.setStyleSheet("")
        self.buttonExit.setObjectName("buttonExit")
        self.gridLayout_3.addWidget(self.buttonExit, 0, 3, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(42, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem6, 0, 4, 1, 1)
        self.gridLayout_2.addWidget(self.groupbox0, 4, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 3, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem7, 1, 0, 1, 1)
        self.label_2.setBuddy(self.groupbox0)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox1.setTitle(_translate("Dialog", "音频采集设备"))
        self.label_2.setText(_translate("Dialog", "HostAPI分类:"))
        self.label.setText(_translate("Dialog", "指定输入设备:"))
        self.groupBox2.setTitle(_translate("Dialog", "设备音频测试"))
        self.buttonDrawVoice.setText(_translate("Dialog", "启动采集"))
        self.checkboxSaveFile.setText(_translate("Dialog", "保留文件"))
        self.buttonRun.setText(_translate("Dialog", "实时识别"))
        self.buttonExit.setText(_translate("Dialog", "退出"))
